### ISSUE TITLE
 点击文件框下方的线（线会变红色），但有时候会没有录入焦点

### ISSUE THREAD

**Issue by tommycom-sudo** [Aspsine/EditTextInListView#1]
1. 点击文件框下方的线（线会变红色），但有时候会没有录入焦点
2. 打开 select page ，点击某一行获取录入焦点,  然后左右滑动到另外一个PAGE，屏幕会不断的闪烁

**Comment by Aspsine** [comment]
@bossno1 

谢谢你的反馈。

可以说一下你的机型和系统版本么？

目前我的机子上面暂没上述问题。

写这个Demo的初衷是 EditText 作为ListView item的演示。

写出来之后，发现蛮像一个笔记本的，然后就多写了几行代码做成了一个笔记本的样子。:)

**Comment by Aspsine** [comment]
针对问题1.我测试的情况是：

A.  EditText长按，会出现你说的情况。

--- EidtText in ListView：
4.3.3 EditText 线变红，有光标，会出现 “文字选择箭头”，但是键盘未弹出。
5.0.1 EditText 线变红，有光标，出现粘贴选项，但是键盘未弹出。

--- EidtText in LinearLayout
4.3.3 EditText 线变红，有光标，会出现 “文字选择箭头”，但是键盘未弹出。
5.0.1 EditText 线变红，有光标，出现粘贴选项，但是键盘未弹出。

以上两种行为对于EditText来说ListView中，和LinearLayout中都是一致的。

B.  对于点击EditText：
4.3.3 和5.0.1都会弹出软键盘，行为基本一致。

结论：长按会让EditText获得焦点，但是不弹软键盘。

我的测试机型：
Galaxy nexus stock android 4.3.3
MX5 flyme 4.5.4.1U android 5.0.1

**Comment by tommycom-sudo** [comment]
感谢大大的回复
第一次用的时候是模拟器，今天我的测试机型：MX5 flyme 5.5.5.10.13 beta Android 5.1
B. 点击EditText
线变红，无光标，键盘弹出 （此时可以录入文字，只是没有光标感觉有点奇怪）
有时候点击右上角的 select page 光标会显示出来（但不是绝对会显示，某些情况下，比如将listview滚动到10行以后）

（select page指示器打开，然后左右滑动在真机上没有闪烁情况出现）

**Comment by tommycom-sudo** [comment]
![s51015-214537](https://cloud.githubusercontent.com/assets/5611689/10515579/afa2c35e-7386-11e5-87ae-a14ab539639b.jpg)
这是能看到光标的情况（光标不会闪烁）

**Comment by Aspsine** [comment]
光标不显示的问题，已修复。
光标的偶尔不闪烁的问题用EditText的公共api可能解决不了。
不提倡使用反射这种黑科技去解决，随着sdk版本升级，可能会埋下一些兼容性问题。

:)

**Comment by tommycom-sudo** [comment]
感谢！！
