### ISSUE TITLE
有时候点击EditText的时候，不会出现光标 （机型为红米Note1s ，系统Android4.4.4）

### ISSUE THREAD

**Issue by hy2012** [Aspsine/EditTextInListView#3]
你好：
在点击EditText的时候，一会有光标，一会没有光标。问题如下截图：
![screenshot_2015-11-10-20-43-21](https://cloud.githubusercontent.com/assets/1439181/11062948/267624fa-87ee-11e5-90a3-f3124b7791ad.png)

**Comment by Aspsine** [comment]
这个问题确实存在。这和EditText内部这个小光标的绘制有关。private的api没法访问，或许用反射可以解决，不过这方面没深入研究。
总结: EditText in ListView的这种方式能不使用尽量不要使用。如果要是用，我这里提供一种不是特别完美的方案。

**Comment by hy2012** [comment]
谢谢~~
